# Generated by Django 5.0.7 on 2024-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('studentid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomonjersey', models.IntegerField()),
                ('studentname', models.TextField()),
                ('position', models.TextField()),
                ('height', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('ldt', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
