# Generated by Django 5.0.7 on 2024-10-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0002_meetups_members_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='height',
        ),
        migrations.RemoveField(
            model_name='members',
            name='ldt',
        ),
        migrations.RemoveField(
            model_name='members',
            name='position',
        ),
    ]
