# Generated by Django 5.0.7 on 2024-10-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0003_remove_members_height_remove_members_ldt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.TextField(default='example@example.com'),
            preserve_default=False,
        ),
    ]
