# Generated by Django 5.0.7 on 2024-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0004_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='nomonjersey',
            field=models.CharField(max_length=100),
        ),
    ]
