# Generated by Django 5.0.7 on 2024-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0005_alter_members_email_alter_members_nomonjersey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('lecturerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lecturername', models.TextField()),
                ('lecturernumber', models.CharField(max_length=20)),
                ('lectureremail', models.CharField(max_length=50)),
                ('lecturerpasword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
