# Generated by Django 5.0.7 on 2024-10-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0006_lecturers_tournament'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Students',
        ),
    ]
