# Generated by Django 5.0.7 on 2024-10-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0007_rename_members_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetups',
            old_name='date',
            new_name='M_date',
        ),
        migrations.RenameField(
            model_name='meetups',
            old_name='Location',
            new_name='M_description',
        ),
        migrations.RenameField(
            model_name='meetups',
            old_name='description',
            new_name='M_location',
        ),
        migrations.RenameField(
            model_name='meetups',
            old_name='time',
            new_name='M_time',
        ),
        migrations.RenameField(
            model_name='meetups',
            old_name='title',
            new_name='M_title',
        ),
    ]
