# Generated by Django 5.0.7 on 2024-10-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_club', '0008_rename_date_meetups_m_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='type',
            new_name='tittle',
        ),
    ]
